name: Cinematic
version: '${project.version}'
main: de.silke.cinematic.Main
api-version: '1.19'
authors: [Silke]
description: Система слежения камеры или кинематографичного режима
website: github.com/blackysky
